# Site Info
site_name: JAudio Studio
site_url: https://vvlpine-stvdios.github.io/JAudio-Studio/
repo_url: https://github.com/Vvlpine-Stvdios/JAudio-Studio
repo_name: JAudio Studio
copyright: Copyright &copy; Vvlpine Stvdios
# Themes
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode
      primary: deep orange
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode
      primary: deep orange
      accent: deep purple

  font:
    text: Roboto
    code: Fira Code
  
  # icon:
  #  logo: 
  # favicon: 
  features:
    - content.tabs.link
    - content.tooltips

    - navigation.expand
    - navigation.footer
    - navigation.path
    - navigation.top
    - navigation.tracking

    - toc.follow
    - toc.integrate

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.arithmatex:
      generic: true



extra_css:
  - stylesheets/header.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js